# Generated by Django 5.0 on 2024-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
