# Generated by Django 5.0 on 2024-01-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_app', '0003_status_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='created_date',
        ),
    ]
