# Generated by Django 5.0 on 2024-01-05 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_app', '0004_rename_date_ordered_order_created_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='qty',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount_upto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_minimum_bill',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis_app.discounttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis_app.discounttype'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('discount', models.FloatField(null=True)),
                ('gst', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField()),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_app.discounttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_app.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_app.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_app.order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_app.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
