# Generated by Django 5.0 on 2024-01-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_app', '0005_discounttype_rename_qty_order_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('minimum_bill', models.FloatField()),
                ('discount_upto', models.FloatField()),
                ('discount', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_app.discounttype')),
            ],
        ),
    ]
