# Generated by Django 5.0 on 2024-01-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_app', '0010_product_category_product_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
